# Generated by Django 3.1.5 on 2021-01-25 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumDodavanja', models.DateTimeField(auto_now_add=True)),
                ('datumIzmene', models.DateTimeField(auto_now=True)),
                ('naziv', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=120)),
                ('mesto', models.CharField(max_length=30)),
                ('datumDodavanja', models.DateTimeField(auto_now_add=True)),
                ('datumIzmene', models.DateTimeField(auto_now=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oglasi.kategorija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumDodavanja', models.DateTimeField(auto_now_add=True)),
                ('datumIzmene', models.DateTimeField(auto_now=True)),
                ('ocena', models.IntegerField()),
                ('tekst', models.CharField(max_length=100)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oglas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oglasi.oglas')),
            ],
        ),
    ]
